tests
mto-2022-pn/lab2_2 pull request #2
Opened 2022-03-25 12:45 UTC by AdrianPietrz

2022-03-28 15:39 UTC, radamuspl requested changes
Nazwy przypadków testowych nic nie mówią o założeniach testów.
Nazwy metod w Javie zaczynamy małą literą.

2022-03-28 15:39 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderBehaviourTest.java
> +public class SimilarityFinderBehaviourTest {
testy zachowania i testy stanu powinny być w jednej klasie - tylko w osobnych metodach.

2022-03-28 15:39 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderBehaviourTest.java
> +    void methodInvokesCountTest() throws NoSuchFieldException, IllegalAccessException {
nazwa testu nic nie mówi o jego założeniach

2022-03-28 15:39 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderTest.java
> +    void SentencesAreEmpty() {
ok, ale co z tego? Czego oczekujemy?

2022-03-30 18:40 UTC, AdrianPietrz commented
Wprowadzono poprawki

2022-04-25 15:17 UTC, radamuspl approved these changes

2022-04-25 15:17 UTC, merged