Lab2_2
mto-2022-pn/lab2_2 pull request #3
Opened 2022-03-25 14:11 UTC by bartekmaka06

indeks: 228805

2022-03-28 15:50 UTC, radamuspl requested changes
Nazwy metod nic nie mówią o logice testu

2022-03-28 15:50 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/BehaviorSimilarityFinderTest.java
> +public class BehaviorSimilarityFinderTest {
testy stanu i zachowania powinny być w tej samej klasie - tylko w odrębnych metodach

2022-03-28 15:50 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/BehaviorSimilarityFinderTest.java
> +    void methodInvokeThreeTimes() throws NoSuchFieldException, IllegalAccessException {
jaka metoda, dlaczego trzy razy - ta nazwa nic nie mówi o logice testu

2022-03-28 15:50 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderTest.java
> +    void TwoSequencesAreEmpty() {
nazwy metod w Javie powinny zaczynać się małą literą/

2022-03-28 19:31 UTC, bartekmaka06 commented
dokonano poprawek

2022-04-25 15:17 UTC, radamuspl approved these changes

2022-04-25 15:18 UTC, merged