Lab2
mto-2022-pn/lab2_2 pull request #4
Opened 2022-03-25 20:49 UTC by pioter00

2022-03-28 15:52 UTC, radamuspl requested changes

2022-03-28 15:52 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderBehaviorTest.java
> +public class SimilarityFinderBehaviorTest {
testy stanu i zachowania powinny być w tej samej klasie - tylko w odrębnych metodach

2022-03-28 15:52 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderBehaviorTest.java
> +    void TestMethodInvokedFourTimes() {
nazwy metod Javie zaczynamy małą literą

2022-03-28 15:52 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderBehaviorTest.java
> +    void TestMethodInvokedZeroTimes() {
ale dlaczego "zerotimes" - nazwa nic nie mówi o logice testu

2022-03-28 16:36 UTC, pioter00 commented
Poprawki do PR'a

2022-04-25 15:22 UTC, radamuspl approved these changes

2022-04-25 15:23 UTC, merged