lab2_2
mto-2022-pn/lab2_2 pull request #5
Opened 2022-03-25 22:51 UTC by piterm11

228800 Piotr Marcinkowski

2022-03-28 15:53 UTC, radamuspl requested changes

2022-03-28 15:53 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderTest.java
> +    void BothSequencesAreEmpty() {
nazwy metod Javie zaczynamy małą literą

2022-03-28 15:53 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderTest.java
> +    void FirstSequenceIsEmpty() {
ok, ale co to powoduje? Nazwa testu mało wyjaśnia

2022-03-28 15:53 UTC, radamuspl commented on src/test/java/edu/iis/mto/similarity/SimilarityFinderTest.java
> +    void InvokesTwoTimes(){
ale co? I dlaczego?

2022-03-28 16:41 UTC, piterm11 commented
Poprawione

2022-04-25 15:24 UTC, radamuspl approved these changes

2022-04-25 15:24 UTC, merged